theme = "hugo-theme-stack"
baseURL = "https://chrisparaiso.dev/"
languageCode = "en-us"
title = "Chris Paraiso"
publishDir = "../cparaiso.github.io/"
[module.hugoVersion]
extended = true
min = "0.87.0"
[menu]
   [[menu.social]]
   identifier = "twitter"
   name = "Twitter"
   url = "https://twitter.com/chrisparaiso"
   [menu.social.params]
   icon = "brand-twitter"
    
   [[menu.social]]
   identifier = "github"
   name = "Github"
   url = "https://github.com/cparaiso"
   [menu.social.params]
   icon = "brand-github"

[params]
mainSections = [ "posts" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2022

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  compact = false
  subtitle = "Full Stack Developer, Father, Gamer, Python, Golang, JavaScript"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.jpg"

  [params.article]
  headingAnchor = false
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = true
  provider = "utterances"

    [params.comments.utterances]
    issueTerm = "pathname"
    repo = "cparaiso/cparaiso.github.io"
    crossorigin = "anonymous"

  [params.widgets]
  homepage = [ ]
  page = [ ]

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true
